version: '3.8'

services:
  neo4j:
    image: neo4j:5.23-community
    container_name: ragforge-.ragforge-43e75148-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
    ports:
      - "7688:7687"  # Bolt
      - "7475:7474"  # HTTP Browser
    volumes:
      - ragforge-.ragforge-43e75148_neo4j_data:/data
      - ragforge-.ragforge-43e75148_neo4j_logs:/logs

volumes:
  ragforge-.ragforge-43e75148_neo4j_data:
  ragforge-.ragforge-43e75148_neo4j_logs:
